### ISSUE TITLE
ROCM macro check error in 'mpi/pt2pt/osu_bw_pipe.c'

### ISSUE THREAD

**Issue by leonf88** [qzan9/osu-micro-benchmarks#2]
如果没有 _ENABLE_ROCM，在 'mpi/pt2pt/osu_bw_pipe.c' 文件中会找不到 HIP_CHECK 和 hipHostMalloc 等宏和函数。

**Comment by qzan9** [comment]
嗯，这只是个小demo，流水线也是写死了的，的确没考虑非ROCm时的build问题。
